import React,{useState,useRef,useEffect,useLayoutEffect} from 'react';import{createRoot}from'react-dom/client';
import{products,categories,money,cleanCart,changeCart,total}from'./shop.js';import{mountMotion}from'./motion.js';
const photos=n=>`assets/${n}.png`;
import{chapters,backgrounds,journeyEnd}from'./journey.js';
import{Subscriptions,Process,Reviews}from'./ReferenceSections.jsx';
function Icon({name}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true">{name==='search'?<><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></>:name==='bag'?<><path d="M5 7h14l1 14H4L5 7Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/></>:name==='heart'?<path d="M20 4c-3-2-6 0-8 2-2-2-5-4-8-2-5 4 1 10 8 16 7-6 13-12 8-16Z"/>:name==='user'?<><circle cx="12" cy="7" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/></>:<path d="M4 7h16M4 12h16M4 17h16"/>}</svg>}
function App(){
 const root=useRef(),dialog=useRef(),opener=useRef(),audio=useRef();const[chapter,setChapter]=useState(0),[nav,setNav]=useState(false),[category,setCategory]=useState('All'),[sort,setSort]=useState('featured'),[query,setQuery]=useState(''),[modal,setModal]=useState(null),[notice,setNotice]=useState(''),[favorites,setFavorites]=useState([]),[sound,setSound]=useState(false),[preview,setPreview]=useState(false);
 const[cart,setCart]=useState(()=>{try{return cleanCart(JSON.parse(localStorage.getItem('noir-cart')))}catch{return{}}});
 useLayoutEffect(()=>mountMotion(root.current,setChapter),[]);
 useEffect(()=>{try{localStorage.setItem('noir-cart',JSON.stringify(cart))}catch{}},[cart]);
 useEffect(()=>{if(modal){dialog.current.showModal();setPreview(false)}else if(dialog.current?.open){dialog.current.close();opener.current?.focus()}},[modal]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),2400);return()=>clearTimeout(id)},[notice]);
 useEffect(()=>()=>audio.current?.close(),[]);
 const open=value=>{opener.current=document.activeElement;setModal(value)};
 const add=id=>{setCart(c=>changeCart(c,id,1));setNotice('Added to your bag')};
 const toggleFavorite=id=>setFavorites(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id]);
 const visible=products.filter(p=>(category==='All'||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:0);
 const count=Object.values(cart).reduce((a,b)=>a+b,0);
 function jumpChapter(index){const el=document.getElementById('home'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced){document.getElementById('products').scrollIntoView();return}window.scrollTo({top:el.offsetTop+(el.offsetHeight-innerHeight)*(index===0?0:(chapters[index].at+.65)/journeyEnd),behavior:'smooth'})}
 async function toggleSound(){if(sound){await audio.current?.suspend();setSound(false);return}try{if(!audio.current){const a=new AudioContext();audio.current=a;const buffer=a.createBuffer(1,a.sampleRate*3,a.sampleRate),data=buffer.getChannelData(0);let previous=0;for(let i=0;i<data.length;i++){previous=(previous+Math.random()*.04-.02)/1.02;data[i]=previous}const source=a.createBufferSource();source.buffer=buffer;source.loop=true;const filter=a.createBiquadFilter();filter.type='lowpass';filter.frequency.value=700;const gain=a.createGain();gain.gain.value=.12;source.connect(filter).connect(gain).connect(a.destination);source.start()}await audio.current.resume();setSound(true)}catch{setNotice('Audio is unavailable in this browser')}}
 function renderCard({product:p,compact=false}){return <article key={p.id} className={`product-card ${compact?'compact':''}`}><div className="product-image"><button className="photo-button" onClick={()=>open({type:'product',product:p})} aria-label={`Quick view ${p.name}`}><img src={photos(p.image)} alt={p.name} loading="lazy"/><span className="quick-view">Quick view <span>↗</span></span></button>{p.badge&&<span className="badge">{p.badge}</span>}<button className={`favorite ${favorites.includes(p.id)?'selected':''}`} aria-label={`${favorites.includes(p.id)?'Unsave':'Save'} ${p.name}`} aria-pressed={favorites.includes(p.id)} onClick={()=>toggleFavorite(p.id)}><Icon name="heart"/></button></div><div className="product-info"><span className="eyebrow">{p.category}</span><button className="product-name" onClick={()=>open({type:'product',product:p})}>{p.name}</button><span className="rating"><span aria-label="Five stars">★★★★★</span> {p.rating}</span><div className="buy-row"><span className="price">{money(p.price).replace('.00','')}</span><button className="gold small" onClick={()=>add(p.id)}>Add to cart <span>↗</span></button></div></div></article>}
 return <div ref={root}><a className="skip-link" href="#products">Skip to products</a><header className="header"><a href="#home" className="logo" aria-label="Blue Tokai home"><span className="bean-mark"/>Blue Tokai</a><nav className={nav?'open':''} aria-label="Main navigation">{[['Home','home'],['Story','story'],['Coffee Journey','home'],['Products','products'],['Subscription','subscription'],['Shop','shop'],['Reviews','reviews'],['Contact','contact']].map(([label,id])=><a key={label} href={`#${id}`} onClick={()=>setNav(false)}>{label}</a>)}</nav><div className="header-actions"><button className="icon-button" aria-label="Search coffee" onClick={()=>open({type:'search'})}><Icon name="search"/></button><button className="icon-button bag-button" aria-label={`Shopping bag, ${count} items`} onClick={()=>open({type:'cart'})}><Icon name="bag"/>{count>0&&<span className="bag-count">{count}</span>}</button><button className="icon-button account" aria-label="Saved coffees" onClick={()=>open({type:'saved'})}><Icon name="user"/></button><a className="gold nav-buy" href="#products">Buy now <span>↗</span></a><button className="icon-button menu-toggle" aria-label="Toggle navigation" aria-expanded={nav} onClick={()=>setNav(!nav)}><Icon name="menu"/></button></div></header>
 <main><section id="home" className="journey" aria-label="From bean to cup"><div className="journey-sticky">
 <div className="intro-atmosphere" aria-hidden="true"><div className="intro-glow"/>{Array.from({length:24},(_,i)=><i className="floating-bean" key={i} style={{'--x':`${(i*37+9)%97}%`,'--y':`${(i*23+13)%99}%`,'--size':`${7+(i*7)%16}px`,'--rotation':`${i*47}deg`,'--delay':`${-i*1.7}s`,'--duration':`${14+i%7}s`}}/>)}</div>
 {backgrounds.map((b,i)=><div className={`journey-photo photo-${i}`} key={b.image} aria-hidden="true"><img src={photos(b.image)} alt="" fetchPriority={i===0?'high':undefined}/><div className="scene-shade"/></div>)}
 {chapters.map(({title,copy},i)=><div className={`journey-scene scene-${i}`} key={i} aria-hidden={chapter!==i}><div className="scene-copy"><span className="eyebrow">{i===0?'Blue Tokai · SINGLE ORIGIN':`0${i+1} — ${['','THE BEAN','THE GRIND','THE HEAT','THE EXTRACTION','THE POUR','THE CUP'][i]}`}</span>{i===0?<h1>{title.split('\n').map((line,n)=><React.Fragment key={line}>{n>0&&<br/>}{line}</React.Fragment>)}</h1>:<h2>{title.split('\n').map((line,n)=><React.Fragment key={line}>{n>0&&<br/>}{line}</React.Fragment>)}</h2>}{copy&&<p>{copy}</p>}{i===0&&<div className="hero-actions"><button className="gold" tabIndex={chapter===i?0:-1} onClick={()=>jumpChapter(1)}>Explore the journey</button><a href="#story" className="text-link" tabIndex={chapter===i?0:-1}>The process</a></div>}{i===6&&<a href="#products" className="gold final-cta" tabIndex={chapter===i?0:-1}>Shop the collection ↗</a>}</div></div>)}
 <div className="journey-bottom"><button className="scroll-prompt" onClick={()=>chapter===6?document.getElementById('products').scrollIntoView({behavior:'smooth'}):jumpChapter(chapter+1)}>SCROLL THE JOURNEY <span/></button></div><div className="chapter-dots" aria-label="Journey scenes">{chapters.map((c,i)=><button key={i} onClick={()=>jumpChapter(i)} className={chapter===i?'active':''} aria-label={`Go to ${c.label}`} aria-current={chapter===i?'step':undefined}/>)}</div></div></section>
 <section id="products" className="section shop-section"><div className="section-heading" data-reveal><div><span className="eyebrow">08 — THE COLLECTION</span><h2>Featured <em>coffee.</em></h2><p>Single-origin beans, signature blends and everything in between — roasted in small batches and shipped within 48 hours.</p></div></div><div className="shop-toolbar"><div className="filters" aria-label="Filter by category">{categories.map(c=><button className={category===c?'active':''} key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="sort">Sort <select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort products"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div>{query&&<div className="search-status">Results for “{query}” <button onClick={()=>setQuery('')}>Clear ×</button></div>}<div className="product-grid" aria-live="polite">{visible.map(p=>renderCard({product:p}))}</div>{!visible.length&&<div className="empty">No coffees found. <button onClick={()=>{setQuery('');setCategory('All')}}>See all products →</button></div>}</section>
 <section className="section category-section" id="shop"><div className="section-heading" data-reveal><h2>Shop by <em>category.</em></h2><span className="eyebrow">09 — YOUR COFFEE, YOUR WAY</span></div><div className="category-grid">{categories.slice(1).map((c,i)=><button key={c} className="category-tile" onClick={()=>{setCategory(c);document.getElementById('products').scrollIntoView({behavior:'smooth'})}}><img src={photos(['beans','espresso','cafe','pour','cafe','bloom'][i])} alt="" loading="lazy"/><span>{c}<small>Explore collection ↗</small></span></button>)}</div></section>
 <Subscriptions onChoose={plan=>open({type:'plan',plan})}/>
 <section id="bestsellers" className="section bestseller"><div className="section-heading" data-reveal><div><span className="eyebrow">11 — THE CROWD FAVOURITES</span><h2>Best <em>sellers.</em></h2></div><a className="text-link" href="#products" onClick={()=>{setCategory('All');setQuery('')}}>View all coffees ↗</a></div><div className="bestseller-grid">{['subscription','beans','set','espresso'].map(id=>renderCard({product:products.find(p=>p.id===id),compact:true}))}</div><div className="collection-rule"/></section>
 <Process/><Reviews/>
 <section id="gallery" className="section reviews"><span className="eyebrow">14 — THE EVERYDAY RITUAL</span><h2>Life in <em>Blue Tokai.</em></h2><p>Slow mornings. Good company. Coffee at the centre.</p><div className="gallery">{['cafe','beans','espresso','pour','bloom','cafe','espresso','beans','bloom','pour','cafe','espresso'].map((img,i)=><button key={i} onClick={()=>open({type:'gallery',image:img})} aria-label={`Open coffee photograph ${i+1}`}><img src={photos(img)} alt={['Coffee shared at a café','Fresh roasted beans','A glass of espresso','The espresso ritual'][i%4]} loading="lazy"/></button>)}</div><p className="gallery-note">EVERY CUP HAS A STORY. MAKE THIS ONE YOURS.</p></section>
 </main><footer className="section footer" id="contact"><div className="footer-top"><div><span className="eyebrow">STAY FOR ANOTHER CUP</span><h2>A little Blue Tokai.<br/><em>In your inbox.</em></h2></div><form onSubmit={e=>{e.preventDefault();setNotice('Thanks! This preview does not send or store email addresses.');e.target.reset()}}><label htmlFor="email">Coffee notes, new roasts, and everyday rituals.</label><div className="email-field"><input id="email" type="email" placeholder="Your email address" required/><button type="submit" aria-label="Join the mailing list">↗</button></div><small>Local preview — no emails are sent.</small></form></div><div className="footer-bottom"><a href="#home" className="logo"><span className="bean-mark"/>Blue Tokai</a><span>Life, beautifully brewed.</span><div><a href="#products">Shop</a><a href="#story">Our story</a><button onClick={()=>open({type:'about'})}>About this preview</button></div><span>© {new Date().getFullYear()} Blue Tokai</span></div></footer>
 <button className={`sound-button ${sound?'playing':''}`} aria-pressed={sound} onClick={toggleSound}><span className="sound-bars"><i/><i/><i/><i/></span>SOUND {sound?'ON':'OFF'}</button><div className="grain" aria-hidden="true"/><div className={`toast ${notice?'visible':''}`} role="status">{notice}</div>
 <dialog ref={dialog} className={`modal ${modal?.type==='gallery'?'image-modal':''}`} onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current){const r=dialog.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)setModal(null)}}} aria-labelledby="modal-title"><button className="close-modal" aria-label="Close dialog" onClick={()=>setModal(null)}>×</button>
 {modal?.type==='product'&&<><img className="detail-image" src={photos(modal.product.image)} alt={modal.product.name}/><span className="eyebrow">{modal.product.category}</span><h2 id="modal-title">{modal.product.name}</h2><p className="gold-text">{modal.product.notes}</p><p>{modal.product.detail}</p><div className="detail-buy"><span className="price">{money(modal.product.price)}</span><button className="gold" onClick={()=>add(modal.product.id)}>Add to bag ↗</button></div></>}
 {modal?.type==='cart'&&<><span className="eyebrow">YOUR NEXT COFFEE MOMENT</span><h2 id="modal-title">Your <em>bag.</em></h2>{count===0?<div className="empty">Your bag is waiting for something good.<button className="gold" onClick={()=>{setModal(null);document.getElementById('products').scrollIntoView({behavior:'smooth'})}}>Explore coffee ↗</button></div>:<>{products.filter(p=>cart[p.id]).map(p=><div className="cart-row" key={p.id}><img src={photos(p.image)} alt=""/><div><strong>{p.name}</strong><small>{money(p.price)}</small><div className="quantity"><button aria-label={`Remove one ${p.name}`} onClick={()=>setCart(c=>changeCart(c,p.id,-1))}>−</button><span>{cart[p.id]}</span><button aria-label={`Add one ${p.name}`} onClick={()=>setCart(c=>changeCart(c,p.id,1))}>+</button></div></div><span>{money(p.price*cart[p.id])}</span></div>)}<div className="cart-total"><span>Subtotal</span><span>{money(total(cart))}</span></div><button className="gold checkout" onClick={()=>setPreview(true)}>Preview order ↗</button>{preview&&<p className="confirmation" role="status">Your selection totals {money(total(cart))}. This is a local shop preview. No order was submitted and no payment was taken.</p>}<p className="fine-print">Demo cart. Ordering and payments are not connected.</p></>}</>}
 {modal?.type==='search'&&<><span className="eyebrow">FIND YOUR FAVOURITE</span><h2 id="modal-title">What’s <em>brewing?</em></h2><form className="search-form" onSubmit={e=>{e.preventDefault();setCategory('All');setModal(null);document.getElementById('products').scrollIntoView({behavior:'smooth'})}}><input type="search" autoFocus aria-label="Search product names" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try espresso or beans…"/><button className="gold">Search ↗</button></form></>}
 {modal?.type==='saved'&&<><h2 id="modal-title">Saved <em>coffees.</em></h2>{favorites.length?products.filter(p=>favorites.includes(p.id)).map(p=><div className="saved-row" key={p.id}><span>{p.name}</span><button className="gold small" onClick={()=>add(p.id)}>Add to bag</button></div>):<p>Tap a heart on any product to keep it here during your visit.</p>}</>}
 {modal?.type==='gallery'&&<><h2 className="sr-only" id="modal-title">Life in Blue Tokai — coffee photograph</h2><img src={photos(modal.image)} alt="Editorial coffee photography"/></>}
 {modal?.type==='plan'&&<><span className="eyebrow">YOUR MONTHLY RITUAL</span><h2 id="modal-title">{modal.plan.name}</h2><p className="plan-price">${modal.plan.price}<small>/month</small></p><ul className="plan-detail">{modal.plan.features.map(feature=><li key={feature}>{feature}</li>)}</ul><p className="confirmation">Subscription preview only. No recurring subscription has been created and no payment is taken.</p><button className="gold" onClick={()=>setModal(null)}>Continue exploring ↗</button></>}
 {modal?.type==='about'&&<><h2 id="modal-title">About this <em>preview.</em></h2><p>A separate recreation based on the supplied reference recording. Photographs are generated replacements; the brewing sequence uses scroll-controlled photographs and transitions. This is not the original site's source or video.</p><p>Review copy is transcribed from the reference and is not verified customer feedback. Unreadable details, product descriptions and the unseen footer are illustrative. The cart stays in this browser. No orders, subscriptions, payments or email messages are sent.</p></>}
 </dialog></div>
}
createRoot(document.getElementById('root')).render(<App/>);
